# Generated by Django 4.2.21 on 2025-06-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_author_alter_post_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="post_files/", verbose_name="File"
            ),
        ),
    ]
