# Generated by Django 4.2.21 on 2025-07-17 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0003_post_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Catégories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Categorie"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(to="blog.category", verbose_name="Catégorie"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="post_files/", verbose_name="Fichier"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="posted",
            field=models.BooleanField(default=False, verbose_name="Publié"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Éditer le"),
        ),
    ]
