# Generated by Django 4.2.21 on 2025-07-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_category_options_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"permissions": [("can_view_all_posts", "Can view all posts")]},
        ),
    ]
