# Generated by Django 5.2.1 on 2025-05-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
