# Generated by Django 4.2.21 on 2025-07-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("can_view_all_posts", "Can view all posts"),
                    ("can_change_all_posts", "Can edit all posts"),
                    ("can_delete_all_posts", "Can change all posts"),
                ],
            },
        ),
    ]
